export type Category = 'History' | 'Science' | 'Inventions' | 'Computers' | 'Languages' | 'General Knowledge';
export type Lesson = { id: string; category: Category; title: string; description: string; difficulty: 'Starter' | 'Growing' | 'Challenge'; minutes: number; offline: boolean; facts: string[]; question: string; options: string[]; answer: number };
export type Translation = { english: string; bangla: string; pronunciation: string; category: string };

export const categories: { name: Category; icon: string; description: string; tone: string }[] = [
  { name: 'History', icon: 'landmark', description: 'People, places, and ideas that shaped our shared story.', tone: 'terracotta' },
  { name: 'Science', icon: 'atom', description: 'Ask why, test ideas, and notice the world around you.', tone: 'green' },
  { name: 'Inventions', icon: 'lightbulb', description: 'Discover the tools that changed how humans live.', tone: 'yellow' },
  { name: 'Computers', icon: 'monitor', description: 'Build confidence with digital literacy and code.', tone: 'blue' },
  { name: 'Languages', icon: 'languages', description: 'Open a door to another person’s words and world.', tone: 'rose' },
  { name: 'General Knowledge', icon: 'sparkles', description: 'Small facts that make a much bigger picture.', tone: 'lavender' }
];

const baseLessons: Lesson[] = [
  ['history-writing', 'History', 'The Story of Ancient Civilizations', 'How early cities, writing, and trade helped communities grow.', 'Growing', 12, true, ['Writing began as a way to track goods.', 'Rivers helped cities grow food and travel.', 'Every civilization contributed ideas we still use.'], 'Which invention helped people keep records?', ['The wheel', 'Writing', 'The telescope', 'The airplane'], 1],
  ['science-electricity', 'Science', 'How Does Electricity Work?', 'Meet the invisible movement that powers a light, a phone, and a school.', 'Starter', 9, true, ['A circuit needs a complete path.', 'Batteries push electric charge.', 'Switches open and close a circuit.'], 'What does a switch do?', ['It opens or closes a circuit', 'It creates sunlight', 'It stores water', 'It measures time'], 0],
  ['invention-telephone', 'Inventions', 'How the Telephone Changed the World', 'Follow a message as it travels from one voice to another.', 'Growing', 11, true, ['Alexander Graham Bell patented a telephone in 1876.', 'Telephones made distant conversation immediate.', 'New inventions usually build on older ideas.'], 'What did the telephone make easier?', ['Growing food', 'Distant conversation', 'Making paper', 'Measuring stars'], 1],
  ['computer-thinking', 'Computers', 'How Computers Think', 'Learn about input, processing, memory, and output through a friendly example.', 'Starter', 10, true, ['The CPU follows instructions.', 'Memory holds information for quick use.', 'Input and output connect people to machines.'], 'What does CPU stand for?', ['Central Processing Unit', 'Computer Personal Utility', 'Central Program User', 'Computer Processing Utility'], 0],
  ['language-words', 'Languages', 'Learn 10 Everyday Words in a New Language', 'Start with greetings, family, food, and the words that make connection possible.', 'Starter', 8, true, ['Hello can be a bridge.', 'Pronunciation guides make a new word less intimidating.', 'Mistakes are part of learning a language.'], 'Which word means hello in Bangla?', ['ধন্যবাদ', 'হ্যালো', 'বই', 'পানি'], 1],
  ['knowledge-sky', 'General Knowledge', 'Why Is the Sky Blue?', 'A tiny journey through light, air, and the colors we see every day.', 'Growing', 7, true, ['Sunlight contains many colors.', 'Air scatters blue light more strongly.', 'The sky changes color at sunrise and sunset.'], 'What reaches our eyes from the Sun?', ['Sound only', 'Sunlight', 'Rain only', 'Wind only'], 1],
  ['science-plants', 'Science', 'How Plants Make Food', 'Explore sunlight, leaves, and the quiet work happening in a garden.', 'Growing', 13, true, ['Leaves capture sunlight.', 'Plants use water and carbon dioxide.', 'Oxygen is released as a useful byproduct.'], 'Which part often captures sunlight?', ['Roots', 'Leaves', 'Seeds', 'Bark'], 1],
  ['history-moon', 'History', 'A Timeline of the Moon Landing', 'See how a question, a team, and a brave mission reached beyond Earth.', 'Challenge', 15, true, ['Apollo 11 landed in 1969.', 'Neil Armstrong was the first person on the Moon.', 'Thousands of people worked on the mission.'], 'In which year did Apollo 11 land?', ['1440', '1876', '1969', '1989'], 2],
  ['computers-safety', 'Computers', 'Your First Guide to Cyber Safety', 'Simple habits for passwords, private information, and asking for help.', 'Starter', 8, true, ['Keep passwords private.', 'Ask a trusted adult before clicking a strange link.', 'Kindness applies online too.'], 'Who can help when something online feels unsafe?', ['A trusted adult', 'A random stranger', 'No one', 'A pop-up ad'], 0],
  ['invention-wheel', 'Inventions', 'The Wheel and the Idea of Movement', 'Why a round shape became one of humanity’s most useful ideas.', 'Starter', 8, true, ['Wheels reduce friction.', 'The idea appears in many cultures.', 'Movement changed trade and travel.'], 'What does a wheel help reduce?', ['Friction', 'Light', 'Sound', 'Memory'], 0],
  ['languages-greetings', 'Languages', 'Greetings Around the World', 'Compare how people welcome one another in five languages.', 'Starter', 6, true, ['A greeting shows respect.', 'Tone and context matter.', 'Learning one phrase can start a friendship.'], 'What is “thank you” in Bangla?', ['ধন্যবাদ', 'সুপ্রভাত', 'বন্ধু', 'স্কুল'], 0],
  ['science-water', 'Science', 'The Journey of a Drop of Water', 'Follow water through clouds, rivers, homes, and living things.', 'Growing', 10, true, ['Water changes state.', 'The water cycle is always moving.', 'Clean water matters for every community.'], 'What process turns water vapor into droplets?', ['Evaporation', 'Condensation', 'Combustion', 'Friction'], 1],
  ['computers-internet', 'Computers', 'What Is the Internet?', 'Understand networks, messages, and why a connection is not guaranteed everywhere.', 'Growing', 12, false, ['The internet connects many networks.', 'A message can travel through many routes.', 'Offline tools matter when connections fail.'], 'What does the internet connect?', ['Only one computer', 'Many networks', 'Only televisions', 'Only printers'], 1],
  ['invention-printing', 'Inventions', 'The Printing Press', 'See how sharing many copies of an idea changed learning across communities.', 'Growing', 10, true, ['Printing made books more available.', 'Ideas travelled farther.', 'Access to knowledge can change lives.'], 'What did printing make easier?', ['Copying ideas', 'Growing crops', 'Flying planes', 'Charging batteries'], 0],
  ['knowledge-stars', 'General Knowledge', 'Reading the Night Sky', 'Learn a few ways people have used stars to travel, wonder, and tell stories.', 'Starter', 7, true, ['Stars helped travelers navigate.', 'Different cultures tell different sky stories.', 'Curiosity connects science and imagination.'], 'What can stars help people do?', ['Navigate', 'Boil water', 'Write code', 'Build roads'], 0],
  ['history-civilizations', 'History', 'Cities Along the River', 'See why rivers became places for food, travel, trade, and new ideas.', 'Growing', 9, true, ['Rivers provide water for people and crops.', 'Trade connects communities.', 'Cities grow through shared systems.'], 'Why were rivers important to early cities?', ['They provided water and travel', 'They stopped all trade', 'They made stars brighter', 'They removed all work'], 0],
  ['science-magnets', 'Science', 'The Invisible Pull of Magnets', 'Test attraction and repulsion while learning how magnets help everyday tools.', 'Starter', 8, true, ['Magnets have north and south poles.', 'Opposite poles attract.', 'Magnetic fields cannot be seen directly.'], 'What happens when opposite poles meet?', ['They attract', 'They disappear', 'They become water', 'They stop gravity'], 0],
  ['invention-compass', 'Inventions', 'The Compass Finds a Direction', 'Understand how a small magnetic needle helped travelers navigate unfamiliar places.', 'Starter', 7, true, ['A compass needle responds to Earth’s magnetic field.', 'Directions help people describe space.', 'Navigation connects science and exploration.'], 'What does a compass help you find?', ['Direction', 'Temperature', 'Language', 'Weight'], 0],
  ['computers-memory', 'Computers', 'Memory and Storage', 'Learn the difference between information a computer is using now and information it saves.', 'Growing', 10, true, ['Memory helps a computer work quickly.', 'Storage keeps files for later.', 'Both are measured in units like bytes.'], 'What keeps a file for later?', ['Storage', 'A mouse', 'A screen', 'A speaker'], 0],
  ['languages-questions', 'Languages', 'Ask a Kind Question', 'Practice simple question words and discover how curiosity sounds in another language.', 'Starter', 7, true, ['Questions help us understand people.', 'Tone can make a question feel welcoming.', 'Practice makes new phrases easier.'], 'What can a question help us do?', ['Understand', 'Hide every idea', 'Stop listening', 'Delete a language'], 0]
].map(([id, category, title, description, difficulty, minutes, offline, facts, question, options, answer]) => ({ id, category, title, description, difficulty, minutes, offline, facts, question, options, answer } as Lesson));
export const lessons = baseLessons;

export const timeline = [
  ['3000 BCE', 'Early Writing', 'Communities began recording trade, stories, and rules.'], ['1440', 'Printing Revolution', 'The printing press helped ideas travel farther.'], ['1769', 'Steam Engine Development', 'New machines changed movement and industry.'], ['1876', 'Telephone', 'Voice could travel across a distance.'], ['1928', 'Penicillin', 'A medical discovery transformed treatment.'], ['1946', 'First General Computer', 'Large machines began automating complex calculations.'], ['1969', 'Moon Landing', 'People reached another world.'], ['1989', 'World Wide Web', 'A new way to share information emerged.'], ['2007', 'Smartphone Era', 'Computing became more portable for many people.'], ['Today', 'Offline Learning', 'The next challenge is making knowledge reachable everywhere.']
].map(([year, title, description]) => ({ year, title, description }));

export const inventions = [
  ['Wheel', 'Ancient world', 'Movement, trade, and transport became easier.'], ['Printing Press', 'c. 1440', 'Books and ideas could be shared at a new scale.'], ['Telescope', '1608', 'People could look deeper into the night sky.'], ['Steam Engine', '1700s', 'Power could move machines and vehicles.'], ['Telephone', '1876', 'Voices could travel across distance.'], ['Light Bulb', '1879', 'Safe electric light changed daily life.'], ['Airplane', '1903', 'Human travel took to the sky.'], ['Computer', '1940s', 'Machines could process information quickly.'], ['Internet', '1960s–90s', 'Networks connected people and knowledge.'], ['Solar Panel', 'Today', 'Sunlight can become useful electricity.']
].map(([name, period, impact]) => ({ name, period, impact }));

export const translations: Translation[] = [
  ['Hello', 'হ্যালো', 'hyā-lo', 'Greetings'], ['Good morning', 'সুপ্রভাত', 'shu-pro-bhat', 'Greetings'], ['Thank you', 'ধন্যবাদ', 'dhon-no-baad', 'Greetings'], ['Friend', 'বন্ধু', 'bon-dhu', 'Family & people'], ['School', 'স্কুল', 'skul', 'School'], ['Book', 'বই', 'boi', 'School'], ['Water', 'পানি', 'pā-ni', 'Everyday'], ['Family', 'পরিবার', 'po-ri-bar', 'Family & people'], ['Food', 'খাবার', 'kha-bar', 'Everyday'], ['Hope', 'আশা', 'a-sha', 'Feelings'], ['Learn', 'শেখা', 'she-kha', 'School'], ['Welcome', 'স্বাগতম', 'swa-gotom', 'Greetings'], ['Sky', 'আকাশ', 'a-kash', 'Nature'], ['Home', 'বাড়ি', 'ba-ri', 'Everyday'], ['Kind', 'দয়ালু', 'do-ya-lu', 'Feelings'], ['Light', 'আলো', 'a-lo', 'Nature'], ['Mother', 'মা', 'ma', 'Family & people'], ['Child', 'শিশু', 'shi-shu', 'Family & people'], ['One', 'এক', 'ek', 'Numbers'], ['Two', 'দুই', 'dui', 'Numbers']
].map(([english, bangla, pronunciation, category]) => ({ english, bangla, pronunciation, category }));

export const achievements = ['First Lesson', 'History Explorer', 'Young Scientist', 'Inventor Explorer', 'Language Starter', 'Computer Beginner', 'Offline Pathfinder', 'Curious Questioner', 'Kind Collaborator', 'Knowledge Builder'];
export const futurePaths = ['Community learning centers', 'Shared tablets', 'School partnerships', 'Offline local servers', 'SD-card learning packs', 'Refurbished devices', 'Low-cost educational hardware', 'NGO partnerships', 'Teacher-led learning hubs'];
