export type Category = 'History' | 'Science' | 'Physics' | 'Chemistry' | 'Biology' | 'Inventions' | 'Computers' | 'Languages' | 'General Knowledge';
export type Lesson = { id: string; category: Category; title: string; description: string; difficulty: 'Starter' | 'Growing' | 'Challenge'; minutes: number; offline: boolean; facts: string[]; question: string; options: string[]; answer: number; visual?: string };
export type Translation = { english: string; bangla: string; pronunciation: string; category: string };

export const categories: { name: Category; icon: string; emoji: string; description: string; tone: string }[] = [
  { name: 'History', icon: 'landmark', emoji: '🏛️', description: 'Cool people and places from long, long ago!', tone: 'terracotta' },
  { name: 'Physics', icon: 'zap', emoji: '⚡', description: 'Why things move, zoom, and go boing!', tone: 'blue' },
  { name: 'Chemistry', icon: 'flask-conical', emoji: '🧪', description: 'Mixing, fizzing, and tiny invisible LEGO bricks!', tone: 'green' },
  { name: 'Biology', icon: 'leaf', emoji: '🌱', description: 'Your body, plants, animals, and how they all work!', tone: 'rose' },
  { name: 'Science', icon: 'atom', emoji: '🔬', description: 'Ask "why?" and discover fun things all around you.', tone: 'green' },
  { name: 'Inventions', icon: 'lightbulb', emoji: '💡', description: 'Amazing ideas that changed how we live!', tone: 'yellow' },
  { name: 'Computers', icon: 'monitor', emoji: '💻', description: 'How computers think, and staying safe online.', tone: 'blue' },
  { name: 'Languages', icon: 'languages', emoji: '🗣️', description: 'Say hello in a brand new language!', tone: 'rose' },
  { name: 'General Knowledge', icon: 'sparkles', emoji: '✨', description: 'Fun facts that will surprise your friends!', tone: 'lavender' }
];

export const techCategories: { name: string; emoji: string; description: string; tone: string; href: string }[] = [
  { name: 'Arduino', emoji: '🔌', description: 'Build with real lights, buttons, and beeps you can touch!', tone: 'blue', href: '/tech/arduino.html' },
  { name: 'ESP32', emoji: '📶', description: 'Like Arduino, but it can talk over Wi-Fi too!', tone: 'blue', href: '/tech/esp32.html' },
  { name: 'Web Development', emoji: '🌐', description: 'Make your very own web page appear like magic!', tone: 'yellow', href: '/tech/webdev.html' },
  { name: 'Blender 3D', emoji: '🧊', description: 'Sculpt toys, tables, and lamps in 3D — for free!', tone: 'terracotta', href: '/tech/blender.html' },
  { name: 'Game Development', emoji: '🎮', description: 'Learn the secret recipe behind every video game.', tone: 'lavender', href: '/tech/gamedev.html' },
  { name: 'Roblox Studio', emoji: '🟥', description: 'Write tiny bits of code to bring your world to life.', tone: 'rose', href: '/tech/roblox.html' },
  { name: 'Processing', emoji: '🖌️', description: 'Draw shapes and animations with code — watch them come alive instantly!', tone: 'yellow', href: '/tech/processing.html' },
  { name: 'Canva', emoji: '🖍️', description: 'Design posters, cards, and logos in your browser — free, no install needed!', tone: 'blue', href: '/tech/canva.html' },
  { name: 'InclusiveCode Academy', emoji: '🎨', description: 'Draw with code and watch it move on screen!', tone: 'green', href: '/academy.html' }
];

const baseLessons: Lesson[] = [
  ['history-writing', 'History', 'The Story of Ancient Civilizations', 'How early cities, writing, and trade helped communities grow.', 'Growing', 12, true, ['Writing began as a way to track goods.', 'Rivers helped cities grow food and travel.', 'Every civilization contributed ideas we still use.'], 'Which invention helped people keep records?', ['The wheel', 'Writing', 'The telescope', 'The airplane'], 1],
  ['science-electricity', 'Science', 'How Does Electricity Work?', 'Meet the invisible movement that powers a light, a phone, and a school.', 'Starter', 9, true, ['A circuit needs a complete path.', 'Batteries push electric charge.', 'Switches open and close a circuit.'], 'What does a switch do?', ['It opens or closes a circuit', 'It creates sunlight', 'It stores water', 'It measures time'], 0],
  ['invention-telephone', 'Inventions', 'How the Telephone Changed the World', 'Follow a message as it travels from one voice to another.', 'Growing', 11, true, ['Alexander Graham Bell patented a telephone in 1876.', 'Telephones made distant conversation immediate.', 'New inventions usually build on older ideas.'], 'What did the telephone make easier?', ['Growing food', 'Distant conversation', 'Making paper', 'Measuring stars'], 1],
  ['computer-thinking', 'Computers', 'How Computers Think', 'Learn about input, processing, memory, and output through a friendly example.', 'Starter', 10, true, ['The CPU follows instructions.', 'Memory holds information for quick use.', 'Input and output connect people to machines.'], 'What does CPU stand for?', ['Central Processing Unit', 'Computer Personal Utility', 'Central Program User', 'Computer Processing Utility'], 0],
  ['language-words', 'Languages', 'Learn 10 Everyday Words in a New Language', 'Start with greetings, family, food, and the words that make connection possible.', 'Starter', 8, true, ['Hello can be a bridge.', 'Pronunciation guides make a new word less intimidating.', 'Mistakes are part of learning a language.'], 'Which word means hello in Bangla?', ['ধন্যবাদ', 'হ্যালো', 'বই', 'পানি'], 1],
  ['knowledge-sky', 'General Knowledge', 'Why Is the Sky Blue?', 'A tiny journey through light, air, and the colors we see every day.', 'Growing', 7, true, ['Sunlight contains many colors.', 'Air scatters blue light more strongly.', 'The sky changes color at sunrise and sunset.'], 'What reaches our eyes from the Sun?', ['Sound only', 'Sunlight', 'Rain only', 'Wind only'], 1],
  ['science-plants', 'Science', 'How Plants Make Food', 'Explore sunlight, leaves, and the quiet work happening in a garden.', 'Growing', 13, true, ['Leaves capture sunlight.', 'Plants use water and carbon dioxide.', 'Oxygen is released as a useful byproduct.'], 'Which part often captures sunlight?', ['Roots', 'Leaves', 'Seeds', 'Bark'], 1],
  ['history-moon', 'History', 'A Timeline of the Moon Landing', 'See how a question, a team, and a brave mission reached beyond Earth.', 'Challenge', 15, true, ['Apollo 11 landed in 1969.', 'Neil Armstrong was the first person on the Moon.', 'Thousands of people worked on the mission.'], 'In which year did Apollo 11 land?', ['1440', '1876', '1969', '1989'], 2],
  ['computers-safety', 'Computers', 'Your First Guide to Cyber Safety', 'Simple habits for passwords, private information, and asking for help.', 'Starter', 8, true, ['Keep passwords private.', 'Ask a trusted adult before clicking a strange link.', 'Kindness applies online too.'], 'Who can help when something online feels unsafe?', ['A trusted adult', 'A random stranger', 'No one', 'A pop-up ad'], 0],
  ['invention-wheel', 'Inventions', 'The Wheel and the Idea of Movement', 'Why a round shape became one of humanity’s most useful ideas.', 'Starter', 8, true, ['Wheels reduce friction.', 'The idea appears in many cultures.', 'Movement changed trade and travel.'], 'What does a wheel help reduce?', ['Friction', 'Light', 'Sound', 'Memory'], 0],
  ['languages-greetings', 'Languages', 'Greetings Around the World', 'Compare how people welcome one another in five languages.', 'Starter', 6, true, ['A greeting shows respect.', 'Tone and context matter.', 'Learning one phrase can start a friendship.'], 'What is “thank you” in Bangla?', ['ধন্যবাদ', 'সুপ্রভাত', 'বন্ধু', 'স্কুল'], 0],
  ['science-water', 'Science', 'The Journey of a Drop of Water', 'Follow water through clouds, rivers, homes, and living things.', 'Growing', 10, true, ['Water changes state.', 'The water cycle is always moving.', 'Clean water matters for every community.'], 'What process turns water vapor into droplets?', ['Evaporation', 'Condensation', 'Combustion', 'Friction'], 1],
  ['computers-internet', 'Computers', 'What Is the Internet?', 'Understand networks, messages, and why a connection is not guaranteed everywhere.', 'Growing', 12, false, ['The internet connects many networks.', 'A message can travel through many routes.', 'Offline tools matter when connections fail.'], 'What does the internet connect?', ['Only one computer', 'Many networks', 'Only televisions', 'Only printers'], 1],
  ['invention-printing', 'Inventions', 'The Printing Press', 'See how sharing many copies of an idea changed learning across communities.', 'Growing', 10, true, ['Printing made books more available.', 'Ideas travelled farther.', 'Access to knowledge can change lives.'], 'What did printing make easier?', ['Copying ideas', 'Growing crops', 'Flying planes', 'Charging batteries'], 0],
  ['knowledge-stars', 'General Knowledge', 'Reading the Night Sky', 'Learn a few ways people have used stars to travel, wonder, and tell stories.', 'Starter', 7, true, ['Stars helped travelers navigate.', 'Different cultures tell different sky stories.', 'Curiosity connects science and imagination.'], 'What can stars help people do?', ['Navigate', 'Boil water', 'Write code', 'Build roads'], 0],
  ['history-civilizations', 'History', 'Cities Along the River', 'See why rivers became places for food, travel, trade, and new ideas.', 'Growing', 9, true, ['Rivers provide water for people and crops.', 'Trade connects communities.', 'Cities grow through shared systems.'], 'Why were rivers important to early cities?', ['They provided water and travel', 'They stopped all trade', 'They made stars brighter', 'They removed all work'], 0],
  ['science-magnets', 'Science', 'The Invisible Pull of Magnets', 'Test attraction and repulsion while learning how magnets help everyday tools.', 'Starter', 8, true, ['Magnets have north and south poles.', 'Opposite poles attract.', 'Magnetic fields cannot be seen directly.'], 'What happens when opposite poles meet?', ['They attract', 'They disappear', 'They become water', 'They stop gravity'], 0],
  ['invention-compass', 'Inventions', 'The Compass Finds a Direction', 'Understand how a small magnetic needle helped travelers navigate unfamiliar places.', 'Starter', 7, true, ['A compass needle responds to Earth’s magnetic field.', 'Directions help people describe space.', 'Navigation connects science and exploration.'], 'What does a compass help you find?', ['Direction', 'Temperature', 'Language', 'Weight'], 0],
  ['computers-memory', 'Computers', 'Memory and Storage', 'Learn the difference between information a computer is using now and information it saves.', 'Growing', 10, true, ['Memory helps a computer work quickly.', 'Storage keeps files for later.', 'Both are measured in units like bytes.'], 'What keeps a file for later?', ['Storage', 'A mouse', 'A screen', 'A speaker'], 0],
  ['languages-questions', 'Languages', 'Ask a Kind Question', 'Practice simple question words and discover how curiosity sounds in another language.', 'Starter', 7, true, ['Questions help us understand people.', 'Tone can make a question feel welcoming.', 'Practice makes new phrases easier.'], 'What can a question help us do?', ['Understand', 'Hide every idea', 'Stop listening', 'Delete a language'], 0]
].map(([id, category, title, description, difficulty, minutes, offline, facts, question, options, answer]) => ({ id, category, title, description, difficulty, minutes, offline, facts, question, options, answer } as Lesson));

const deepDiveLessons: Lesson[] = [
  { id: 'physics-motion', category: 'Physics', title: "Why Don't Things Stop By Themselves?", description: 'Push a toy car and watch it zoom! Discover the fun rules behind every push and pull.', difficulty: 'Starter', minutes: 7, offline: true, facts: ['A ball won’t start rolling all by itself — it needs a push!', 'Push something harder, and it zooms away faster.', 'When you jump, you push down and the ground pushes you back up — pushes love to come in pairs!'], question: 'A toy car is rolling on a smooth floor. What makes it stop?', options: ['Something bumps it or rubs against it, like your hand or the rug', 'It stops all by itself for no reason', 'The car gets tired', 'It never stops, ever'], answer: 0, visual: 'physics-motion' },
  { id: 'physics-circuits', category: 'Physics', title: 'How Do Lights Turn On?', description: 'Follow the secret path electricity takes to make a tiny lightbulb glow!', difficulty: 'Growing', minutes: 8, offline: true, facts: ['Electricity needs a complete loop to flow — like a circle with no gaps.', 'A battery is like a tiny pump that pushes electricity all the way around.', 'If a wire snaps or a bulb breaks, it’s like a clog in a pipe — the flow stops!'], question: 'What does a battery do in a circuit?', options: ['Pushes electricity around, like a pump', 'Blocks all the electricity', 'Makes the wire taste sweet', 'Paints the wire a new color'], answer: 0, visual: 'physics-circuit' },
  { id: 'physics-energy', category: 'Physics', title: 'The Magic of a Swing: Up and Down!', description: 'Watch a swing soar up and whoosh back down — where does its energy hide in between?', difficulty: 'Starter', minutes: 7, offline: true, facts: ['At the very top of a swing, you’re storing "waiting energy," like a stretched rubber band.', 'Swooshing back down, that waiting energy turns into "zoom energy" — the energy of moving fast!', 'Energy never just disappears — it only changes from one kind into another.'], question: 'When a swing is way up high and about to fall, what does it have the MOST of?', options: ['Waiting energy, ready to move', 'Zoom energy, already racing', 'No energy at all', 'Sound energy'], answer: 0, visual: 'physics-energy' },
  { id: 'physics-waves', category: 'Physics', title: 'Ripples, Wiggles, and Waves!', description: 'Drop a pebble in a pond and watch the ripples spread — sound and light wiggle the very same way!', difficulty: 'Growing', minutes: 7, offline: true, facts: ['A wave is just something wiggling back and forth, again and again.', 'Wiggles close together move fast; wiggles far apart move slow.', 'Tall, big wiggles carry more energy than short, gentle ones.'], question: 'What happens if you drop a big rock into a pond instead of a tiny pebble?', options: ['The ripples are much bigger and taller', 'There are no ripples at all', 'The pond disappears', 'The water changes color'], answer: 0, visual: 'physics-wave' },

  { id: 'chem-atoms', category: 'Chemistry', title: 'Tiny LEGO Bricks Called Atoms', description: 'Your toys, your dog, and even YOU are built from super tiny building blocks called atoms!', difficulty: 'Starter', minutes: 7, offline: true, facts: ['Atoms are so tiny, you can’t see even one — not even with your sharpest eyes!', 'Every atom has a busy little center, with even tinier bits zooming around it.', 'There are only about 100 different kinds of atoms — but mixed together, they make EVERYTHING!'], question: 'What are the tiny building blocks that make up everything around us called?', options: ['Atoms', 'Pixels', 'Crumbs', 'Bubbles'], answer: 0, visual: 'chem-atom' },
  { id: 'chem-states', category: 'Chemistry', title: 'Ice, Water, Steam: Same Stuff, Different Moves!', description: 'An ice cube, a glass of water, and steam from hot cocoa all look different — but they’re secretly twins!', difficulty: 'Starter', minutes: 6, offline: true, facts: ['In ice, the tiny bits are frozen in place, packed close, like kids standing still in a line.', 'In water, the tiny bits slide and wiggle past each other, like kids walking around a room.', 'In steam, the tiny bits zoom around wildly, like kids running all over the playground!'], question: 'In which one do the tiny bits move around the MOST freely?', options: ['Steam', 'Ice', 'Water', 'None of them move'], answer: 0, visual: 'chem-states' },
  { id: 'chem-reactions', category: 'Chemistry', title: 'Mixing Magic: When Stuff Becomes NEW Stuff!', description: 'Mix baking soda and vinegar and — fizzzz! You just turned old stuff into brand new stuff.', difficulty: 'Growing', minutes: 7, offline: true, facts: ['When things mix and turn into something totally different, that’s a chemical reaction.', 'Toast turning brown, a sparkler glowing, and a bike getting rusty are all chemical reactions!', 'Scientists write these changes down like a little recipe card.'], question: 'What do we call it when ingredients mix and turn into something brand new?', options: ['A chemical reaction', 'A magic trick', 'A shortcut', 'A shadow'], answer: 0, visual: 'chem-reaction' },
  { id: 'chem-ph', category: 'Chemistry', title: 'Sour or Soapy? A Fun Number Scale!', description: 'Lemons taste super sour, soap feels slippery-smooth — scientists made a number scale just for this!', difficulty: 'Growing', minutes: 6, offline: true, facts: ['Lemon juice and vinegar are sour — scientists call sour stuff "acidic."', 'Soap and baking soda feel soapy — scientists call that "basic."', 'Plain water sits right in the middle — not sour, not soapy. We call that "neutral."'], question: 'What do scientists call plain water, right in the middle of the scale?', options: ['Neutral', 'Super sour', 'Extra soapy', 'Sweet'], answer: 0, visual: 'chem-ph' },

  { id: 'bio-cell', category: 'Biology', title: "You're Made of Trillions of Tiny Rooms!", description: 'Your whole body — and every living thing — is built from teeny building blocks called cells!', difficulty: 'Starter', minutes: 7, offline: true, facts: ['A cell is like a tiny room with its own special job to do.', 'Every cell has a control center called the nucleus, like a tiny captain giving directions.', 'You have TRILLIONS of cells all working together to make just one you!'], question: 'What do we call the tiny building blocks that make up your whole body?', options: ['Cells', 'Pixels', 'Dots', 'Crumbs'], answer: 0, visual: 'bio-cell' },
  { id: 'bio-photosynthesis', category: 'Biology', title: 'How Plants Cook Their Own Lunch!', description: 'Plants don’t carry a lunchbox — they cook their own food using pure sunshine!', difficulty: 'Growing', minutes: 7, offline: true, facts: ['Plants catch sunlight with their green leaves, like tiny solar panels.', 'They mix sunlight with water and air to cook up their own sugary food.', 'As a bonus, plants breathe out oxygen — the same air that you and I breathe in!'], question: 'What do plants breathe out that helps you and me breathe?', options: ['Oxygen', 'Smoke', 'Bubbles', 'Glue'], answer: 0, visual: 'bio-photosynthesis' },
  { id: 'bio-body', category: 'Biology', title: "Meet Your Body's Amazing Teams!", description: 'Your body is like a superhero squad — your heart, lungs, and tummy all have special jobs!', difficulty: 'Growing', minutes: 8, offline: true, facts: ['Your heart and blood are like a delivery truck, carrying air and food all around your body.', 'Your lungs breathe in fresh air and breathe out the air you don’t need anymore.', 'Your tummy breaks food down into tiny bits your body can use for energy.'], question: 'Which part of your body works like a delivery truck?', options: ['Your heart and blood', 'Your lungs', 'Your tummy', 'Your hair'], answer: 0, visual: 'bio-body' },
  { id: 'bio-foodchain', category: 'Biology', title: 'Who Eats Who? The Food Chain Game!', description: 'The sun feeds the grass, the grass feeds the rabbit, and the rabbit feeds the fox — follow the chain!', difficulty: 'Starter', minutes: 6, offline: true, facts: ['Plants get their energy straight from the sun — they don’t need to eat anything else!', 'Animals like rabbits eat plants to get their energy.', 'Animals like foxes eat OTHER animals to get their energy.'], question: 'Where does a plant get its energy from?', options: ['The sun', 'A rabbit', 'A fox', 'The ground only'], answer: 0, visual: 'bio-foodchain' },
];

export const lessons = baseLessons.concat(deepDiveLessons);

export const timeline = [
  ['3000 BCE', 'Early Writing', 'Communities began recording trade, stories, and rules.'], ['1440', 'Printing Revolution', 'The printing press helped ideas travel farther.'], ['1769', 'Steam Engine Development', 'New machines changed movement and industry.'], ['1876', 'Telephone', 'Voice could travel across a distance.'], ['1928', 'Penicillin', 'A medical discovery transformed treatment.'], ['1946', 'First General Computer', 'Large machines began automating complex calculations.'], ['1969', 'Moon Landing', 'People reached another world.'], ['1989', 'World Wide Web', 'A new way to share information emerged.'], ['2007', 'Smartphone Era', 'Computing became more portable for many people.'], ['Today', 'Offline Learning', 'The next challenge is making knowledge reachable everywhere.']
].map(([year, title, description]) => ({ year, title, description }));

export const inventions = [
  ['Wheel', 'Ancient world', 'Movement, trade, and transport became easier.'], ['Printing Press', 'c. 1440', 'Books and ideas could be shared at a new scale.'], ['Telescope', '1608', 'People could look deeper into the night sky.'], ['Steam Engine', '1700s', 'Power could move machines and vehicles.'], ['Telephone', '1876', 'Voices could travel across distance.'], ['Light Bulb', '1879', 'Safe electric light changed daily life.'], ['Airplane', '1903', 'Human travel took to the sky.'], ['Computer', '1940s', 'Machines could process information quickly.'], ['Internet', '1960s–90s', 'Networks connected people and knowledge.'], ['Solar Panel', 'Today', 'Sunlight can become useful electricity.']
].map(([name, period, impact]) => ({ name, period, impact }));

export const translations: Translation[] = [
  ['Hello', 'হ্যালো', 'hyā-lo', 'Greetings'], ['Good morning', 'সুপ্রভাত', 'shu-pro-bhat', 'Greetings'], ['Thank you', 'ধন্যবাদ', 'dhon-no-baad', 'Greetings'], ['Friend', 'বন্ধু', 'bon-dhu', 'Family & people'], ['School', 'স্কুল', 'skul', 'School'], ['Book', 'বই', 'boi', 'School'], ['Water', 'পানি', 'pā-ni', 'Everyday'], ['Family', 'পরিবার', 'po-ri-bar', 'Family & people'], ['Food', 'খাবার', 'kha-bar', 'Everyday'], ['Hope', 'আশা', 'a-sha', 'Feelings'], ['Learn', 'শেখা', 'she-kha', 'School'], ['Welcome', 'স্বাগতম', 'swa-gotom', 'Greetings'], ['Sky', 'আকাশ', 'a-kash', 'Nature'], ['Home', 'বাড়ি', 'ba-ri', 'Everyday'], ['Kind', 'দয়ালু', 'do-ya-lu', 'Feelings'], ['Light', 'আলো', 'a-lo', 'Nature'], ['Mother', 'মা', 'ma', 'Family & people'], ['Child', 'শিশু', 'shi-shu', 'Family & people'], ['One', 'এক', 'ek', 'Numbers'], ['Two', 'দুই', 'dui', 'Numbers']
].map(([english, bangla, pronunciation, category]) => ({ english, bangla, pronunciation, category }));

export const achievements = ['First Lesson', 'History Explorer', 'Young Scientist', 'Inventor Explorer', 'Language Starter', 'Computer Beginner', 'Offline Pathfinder', 'Curious Questioner', 'Kind Collaborator', 'Knowledge Builder'];
export const futurePaths = ['Community learning centers', 'Shared tablets', 'School partnerships', 'Offline local servers', 'SD-card learning packs', 'Refurbished devices', 'Low-cost educational hardware', 'NGO partnerships', 'Teacher-led learning hubs'];
